#!/bin/bash
# Guide for API documentation generation

echo "📝 API Documentation Generation"
echo "================================"
echo ""
echo "ComposeWebView uses manual API documentation in docs/api/"
echo ""
echo "Current API docs:"
echo "  - docs/api/compose-webview.md  (Main API reference)"
echo "  - docs/api/types.md            (Types reference)"
echo ""
echo "=============================================="
echo "Manual Documentation Process:"
echo "=============================================="
echo ""
echo "1. Add KDoc to public APIs in source code"
echo "   /**"
echo "    * Brief description."
echo "    *"
echo "    * @param param Description"
echo "    * @return Description"
echo "    */"
echo ""
echo "2. Create/update markdown file in docs/api/"
echo "   - Use template: .agent/skills/documentation/templates/api_doc_template.md"
echo ""
echo "3. Include code examples with syntax highlighting"
echo ""
echo "4. Add to mkdocs.yml navigation"
echo ""
echo "=============================================="
echo "Automated Generation (Future Enhancement):"
echo "=============================================="
echo ""
echo "For automated API documentation, consider integrating Dokka:"
echo ""
echo "1. Add Dokka plugin to build.gradle.kts:"
echo "   plugins {"
echo "       id(\"org.jetbrains.dokka\") version \"1.9.10\""
echo "   }"
echo ""
echo "2. Generate docs:"
echo "   ./gradlew dokkaHtml        # HTML output"
echo "   ./gradlew dokkaGfm         # GitHub Flavored Markdown"
echo ""
echo "3. Integrate with MkDocs:"
echo "   - Copy generated markdown to docs/api/"
echo "   - Or use mkdocs-gen-files plugin"
echo ""
echo "=============================================="
echo "Current Workflow (Recommended):"
echo "=============================================="
echo ""
echo "1. Ensure all public APIs have KDoc comments"
echo "2. Run KDoc verification:"
echo "   bash .agent/skills/code-review/scripts/verify_kdoc.sh"
echo ""
echo "3. Manually document APIs in docs/api/"
echo "   - Provides better control over examples and explanations"
echo "   - More user-friendly than auto-generated docs"
echo ""
echo "4. Validate and build:"
echo "   bash .agent/skills/documentation/scripts/validate_docs.sh"
echo "   bash .agent/skills/documentation/scripts/mkdocs_build.sh"
echo ""
echo "================================"
echo "✅ See manual API doc template:"
echo "   .agent/skills/documentation/templates/api_doc_template.md"
echo "================================"
